---
baseURL: https://rubenerd.com/
disableLiveReload: true
editor: vim
languageCode: en-SG
rssLimit: 10
theme: rubenerd-rubi
title: Rubenerd

markup:
  goldmark:
    extensions:
      typeographer: true
    renderer:
      unsafe: true
      xHTML: true

params:

  author:
    city: Sydney
    country: Australia
    first: Ruben
    foaf: foaf.rdf
    gender: Male
    gitlab: rubenerd
    home: http://rubenschade.com/
    last: Schade
    nationality: Australian
    partner: http://kirinyan.net/
    place: https://en.wikipedia.org/wiki/Sydney
    state: New South Wales
    twitter: rubenerd
    why: These map to schema.org data.
    bio: '<p><img src="https://rubenerd.com/files/2017/me.jpg" alt="Me!" style="float:right; margin:0 0 1em 2em; height:96px; width:96px;" /></p><p>Ruben Schade is a rare breed of spruce tree requiring nothing but pine ice-cream cones for nourishment. His hobbies include predictive branching, Ad Lib barking, and leafing through manuals. Find out more about Ruben and his roots <a href="/about/">on the About page</a>.</p>'
    support: '<p>I donâ€™t run ads  or tracking here. If you found this post helpful or entertaining, you can <a style="font-weight:bold" href="https://www.ko-fi.com/A625HL">buy me a coffee</a>, or I have a <a href="https://www.amazon.com.au/hz/wishlist/ls/3RCH3JFZIEVE3/ref=nav_wishlist_lists_1?_encoding=UTF8&type=wishlist">silly wish list</a>. Thanks!</p>'

  award: The First Annual Montgomery Burns Award for Outstanding Achievement in the Field of Excellence.
  description: By Ruben Schade in s/ Singapore/ Sydney/ since 2004-ish.
  inception: 2004
  keywords: australia,singapore,sydney,anime,apple,tech,freebsd,travel,coffee
  logo: logo.png
  logo_rss: rss.png
  source: https://gitlab.com/rubenerd/rubenerd.com/blob/master/
  twitter: rubenerd_blog

  podcast:
    category: show
    cover: http://showfeed.rubenerd.com/itunes-cover.png
    explicit: clean
    feed: http://showfeed.rubenerd.com/
    itunes: https://itunes.apple.com/au/podcast/rubenerd-show/id1003680071
    itunes_category: Society & Culture
    itunes_sub: Personal Journals
    licence_title: Creative Commons Attribution 3.0
    licence_url: https://creativecommons.org/licenses/by/3.0/
    keywords: australia,sydney,singapore,thoughts,tech,anime,jazz,ruben schade,onsug,overnightscape underground
    overcast: https://overcast.fm/itunes1003680071/rubenerd-show
    pocket_casts: http://pca.st/ybXl
    publisher: me@rubenschade.com
    summary: A long-running harmless podcast of observations from Singapore, Malaysia, and Australia.
    tagline: A harmless show of observations, since 2005
    title: Rubenerd Show

menu:
  header:
  - identifier: home
    name: Latest posts
    title: Home
    url: /
    weight: 1
    identifier: about
  - name: Author, dedication, and site information
    title: About
    url: /about/
    weight: 2
  - identifier: archives
    name: Lists of all posts by year, category, and writing location
    title: Archives
    url: /archives/
    weight: 3
  - identifier: podcast
    name: My harmless podcast of observations
    title: Podcast
    url: /show/
    weight: 4
  - identifier: omake
    name: Extra goodies
    title: Omake
    url: /omake-pages/
    weight: 5

permalinks:
  omake: /omake/:filename/
  page: /:filename/
  post: /:filename/

taxonomies:
  category: category
  location: location
  tag: tag
  year: year

disableKinds:
- categories
- section
- sections
- tags

